FROM rocker/verse:4.2.1
RUN apt-get update && apt-get install -y  cmake gdal-bin git-core imagemagick jags libcurl4-openssl-dev libgdal-dev libgeos-dev libgeos++-dev libgit2-dev libgl1-mesa-dev libglu1-mesa-dev libicu-dev libnetcdf-dev libpng-dev libproj-dev libssl-dev libudunits2-dev libxml2-dev make pandoc pandoc-citeproc zlib1g-dev && rm -rf /var/lib/apt/lists/*
RUN mkdir -p /usr/local/lib/R/etc/ /usr/lib/R/etc/
RUN echo "options(repos = c(CRAN = 'https://cran.rstudio.com/'), download.file.method = 'libcurl', Ncpus = 4)" | tee /usr/local/lib/R/etc/Rprofile.site | tee /usr/lib/R/etc/Rprofile.site
RUN R -e 'install.packages("remotes")'
RUN Rscript -e 'remotes::install_version("RColorBrewer",upgrade="never", version = "1.1-3")'
RUN Rscript -e 'remotes::install_version("colorspace",upgrade="never", version = "2.0-3")'
RUN Rscript -e 'remotes::install_version("viridisLite",upgrade="never", version = "0.4.1")'
RUN Rscript -e 'remotes::install_version("plot3D",upgrade="never", version = "1.4")'
RUN Rscript -e 'remotes::install_version("kernlab",upgrade="never", version = "0.9-31")'
RUN Rscript -e 'remotes::install_version("scales",upgrade="never", version = "1.2.1")'
RUN Rscript -e 'remotes::install_version("purrr",upgrade="never", version = "0.3.5")'
RUN Rscript -e 'remotes::install_version("ggplot2",upgrade="never", version = "3.3.6")'
RUN Rscript -e 'remotes::install_version("sp",upgrade="never", version = "1.5-0")'
RUN Rscript -e 'remotes::install_version("stringr",upgrade="never", version = "1.4.1")'
RUN Rscript -e 'remotes::install_version("base64enc",upgrade="never", version = "0.1-3")'
RUN Rscript -e 'remotes::install_version("shiny",upgrade="never", version = "1.7.2")'
RUN Rscript -e 'remotes::install_version("rmarkdown",upgrade="never", version = "2.17")'
RUN Rscript -e 'remotes::install_version("knitr",upgrade="never", version = "1.40")'
RUN Rscript -e 'remotes::install_version("rstudioapi",upgrade="never", version = "0.14")'
RUN Rscript -e 'remotes::install_version("e1071",upgrade="never", version = "1.7-11")'
RUN Rscript -e 'remotes::install_version("ggrepel",upgrade="never", version = "0.9.1")'
RUN Rscript -e 'remotes::install_version("DT",upgrade="never", version = "0.25")'
RUN Rscript -e 'remotes::install_version("data.table",upgrade="never", version = "1.14.2")'
RUN Rscript -e 'remotes::install_version("shinydashboard",upgrade="never", version = "0.7.2")'
RUN Rscript -e 'remotes::install_version("DBI",upgrade="never", version = "1.1.3")'
RUN Rscript -e 'remotes::install_version("vegan",upgrade="never", version = "2.6-4")'
RUN Rscript -e 'remotes::install_version("raster",upgrade="never", version = "3.6-3")'
RUN Rscript -e 'remotes::install_version("ggpubr",upgrade="never", version = "0.4.0")'
RUN Rscript -e 'remotes::install_version("dendextend",upgrade="never", version = "1.16.0")'
RUN Rscript -e 'remotes::install_version("shinyjs",upgrade="never", version = "2.1.0")'
RUN Rscript -e 'remotes::install_version("readxl",upgrade="never", version = "1.4.1")'
RUN Rscript -e 'remotes::install_version("kohonen",upgrade="never", version = "3.0.11")'
RUN Rscript -e 'remotes::install_version("writexl",upgrade="never", version = "1.4.0")'
RUN Rscript -e 'remotes::install_version("wesanderson",upgrade="never", version = "0.3.6")'
RUN Rscript -e 'remotes::install_version("subniche",upgrade="never", version = "1.5")'
RUN Rscript -e 'remotes::install_version("sortable",upgrade="never", version = "0.4.6")'
RUN Rscript -e 'remotes::install_version("shinyWidgets",upgrade="never", version = "0.7.4")'
RUN Rscript -e 'remotes::install_version("shinyTree",upgrade="never", version = "0.2.7")'
RUN Rscript -e 'remotes::install_version("shinyjqui",upgrade="never", version = "0.4.1")'
RUN Rscript -e 'remotes::install_version("shinydashboardPlus",upgrade="never", version = "2.0.3")'
RUN Rscript -e 'remotes::install_version("shinycssloaders",upgrade="never", version = "1.0.0")'
RUN Rscript -e 'remotes::install_version("shinybusy",upgrade="never", version = "0.3.1")'
RUN Rscript -e 'remotes::install_version("shinyBS",upgrade="never", version = "0.61.1")'
RUN Rscript -e 'remotes::install_version("sf",upgrade="never", version = "1.0-8")'
RUN Rscript -e 'remotes::install_version("segRDA",upgrade="never", version = "1.0.2")'
RUN Rscript -e 'remotes::install_version("rintrojs",upgrade="never", version = "0.3.2")'
RUN Rscript -e 'remotes::install_version("rgl",upgrade="never", version = "0.110.2")'
RUN Rscript -e 'remotes::install_version("randomForestExplainer",upgrade="never", version = "0.10.1")'
RUN Rscript -e 'remotes::install_version("pdp",upgrade="never", version = "0.8.1")'
RUN Rscript -e 'remotes::install_version("oceanmap",upgrade="never", version = "0.1.1")'
RUN Rscript -e 'remotes::install_version("Metrics",upgrade="never", version = "0.1.4")'
RUN Rscript -e 'remotes::install_version("klaR",upgrade="never", version = "1.7-1")'
RUN Rscript -e 'remotes::install_version("imputeMissings",upgrade="never", version = "0.0.3")'
RUN Rscript -e 'remotes::install_version("gstat",upgrade="never", version = "2.0-9")'
RUN Rscript -e 'remotes::install_version("gplots",upgrade="never", version = "3.1.3")'
RUN Rscript -e 'remotes::install_version("golem",upgrade="never", version = "0.3.4")'
RUN Rscript -e 'remotes::install_version("ggthemes",upgrade="never", version = "4.2.4")'
RUN Rscript -e 'remotes::install_version("ggridges",upgrade="never", version = "0.5.4")'
RUN Rscript -e 'remotes::install_version("geodist",upgrade="never", version = "0.0.7")'
RUN Rscript -e 'remotes::install_version("gbm",upgrade="never", version = "2.1.8.1")'
RUN Rscript -e 'remotes::install_version("factoextra",upgrade="never", version = "1.0.7")'
RUN Rscript -e 'remotes::install_version("colourpicker",upgrade="never", version = "1.1.1")'
RUN Rscript -e 'remotes::install_version("colorRamps",upgrade="never", version = "2.3.1")'
RUN Rscript -e 'remotes::install_version("cicerone",upgrade="never", version = "1.0.4")'
RUN Rscript -e 'remotes::install_version("caret",upgrade="never", version = "6.0-93")'
RUN Rscript -e 'remotes::install_version("beepr",upgrade="never", version = "1.3")'
RUN Rscript -e 'remotes::install_version("aweSOM",upgrade="never", version = "1.3")'
RUN Rscript -e 'remotes::install_github("DaniloCVieira/iMESc3.0", upgrade ="never")'
RUN mkdir /build_zone
ADD . /build_zone
WORKDIR /build_zone
RUN R -e 'remotes::install_local(upgrade="never")'
RUN rm -rf /build_zone
EXPOSE 80
CMD R -e "options('shiny.port'=80,shiny.host='0.0.0.0');imesc::run_app()"
