options(shiny.autoload.r=FALSE)
utils::globalVariables(c(
"Dim.1","Dim.2","EBNB","Feature","Importance","Metric","NB","NP","RFerror_class","RFerror_reg","Read_Shapefile","abline","accu_rf_class","accu_rf_reg","accu_rf_reg_model","accu_som_class","addlayer","agg_icon2","aggregate","ave","b64","bag_mp","bag_name_new","bag_somname","bag_sompred_eX","bag_sompred_eY","bmu_plot","capture.output","check_model","check_model0","check_model_caret","citation","clusGap","cmdscale","colorRampPalette","comb_feaimp","combn","comp_icon","compareVersion","compare_icon","coolBlueHotRed","cordata_filter","data.rares_fun","data_migrate","data_migrate2","datalist_render","datalist_som_errorsX","datalist_som_errorsY","datastr","dev.off","dialogmodal","div_icon","dtable_som","ensemble_find","ensemble_find_auc","ensemble_find_metrics","ensemble_find_probs","ensemble_icon","errors_som","excel_sheets","extendrange","figdim","flattenlist","fviz_gap_stat","getClass_wei","getConfusion","getDistancePointers","getHelp","getReg_wei","get_correct_predsom","get_data_map","get_down","get_en_method","get_ensemble_pred","get_faclevels","get_feature_data_plot","get_feature_data_plot_ensemble","get_inter_metrics_tabs","get_neurons","get_neurons_hc","get_obs_erros_ensemble_class","get_qclass_ord","get_saved_models","get_selfactors","get_sompred_results","get_weights_from","getargs_plot_scoreloss","getbp_som","getbp_som2","getclassmat","getcol_missing","getcolhabs","getcopoints","getdata_model","getdown","getinter_grid","getmodelist","getmodelist_names","getmodelist_pd1","getmodelist_pd2","getrf","getroot","getrow_missing","getsig_aculoss","getsigs2_loss","gettrain","gettree","gg_factors","gg_pairplot","gg_pairplot2","ggbox","gghistogram","ggmds","ggpca","ggrda","graphics.off","grid","group","head","help","hist","i_corplot","id","image","imesc_icon","inline","interact_ensemble_each",
"is.factor.matrix","is_scaled_return_scaled","jpeg","js_getid","js_tip","jscode_screen","kmeans","kmeans_icon","knn_icon","last_update","layout","legend","lines","loop_pd3","match_col","median","mergedatacol","multipimp","mymat","mytips","na.omit","na_icon","nadata","name_niche","navPage","nb_icon","neu","newcolhabs","nmissing","ns_tab5","object.size","pUmatrix","packageDescription",
"par","pbox","pchanges","pclus","pcorr","pcounts","pd_predfun_ensemble","pdf","pdp_ensemble","permimp_metric","permimp_metric_ensemble","permute_importance_each_ensemble","permute_importance_each_progress","phist","plot.new","plot.som_grid","plotCM","plot_florest_class","plot_interframe","plot_model_features","plot_pd_groups","plot_ridges","plot_varimport","plotest_qclass","plothists","plotnetwork","plotnetwork_list","plotshape","pnb","png","points","pophelp","pproperty","ppsummary","prcomp","prda","pred_factors","predcomb_table","predict",
"predsom_name","prepare_factors","prf","pwRDA2","quantile","rand_inter_ensemble","read_excel","recordPlot","rel.inf","reorder","replayPlot","resampName","rescale_copoints","rf_icon","rf_rank","rf_rel","runif","savebinary","saveclusters","savecodebook","savediscrete","savediv","savemapcode","saveniche","saveordinal","saverare","savesom","savesompred","scale_color_2","sd","sgboost_icon","sig","sig_feature","sig_feature_ensemble","smw.root2","somQuality4","somplot_args","spineplot","split_icon","stats_ml","str","str_numerics","str_numerics3","sup_icon","svg","svm_icon","t.test_inter_ensemble","test_data","textauthors","textbase","textbphelp","textclustering","textcoords","texthclust","textinput","textintro","textlab","textlayer","textmdshelp","textpcahelp","textremove","textrfbphelp","textscale","textscreeplot","textseed","textupload","textvotes","tiff","tiphelp","tiphelp3","topo.colors","topology","training_data","transf_df","transfmodal","tree_func","unregister_dopar","unsup_icon","validate_data","value","var","variable","weighted.mean","wrapRF","write.table","x","xdim","xyf_icon","y","ydim","zip",
'interact_ensemble_foreach', 'myformat',
'permute_importance_foreach_ensemble',
'permute_importance_foreach_progress' ,'plotforest_qclass'
))




